// <auto-generated />
using System;
using Customers.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customers.Infrastructure.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260503062700_Customer_RemoveUserRelatedFields")]
    partial class Customer_RemoveUserRelatedFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Bday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers", "customers");
                });

            modelBuilder.Entity("Customers.Domain.Entities.Customer", b =>
                {
                    b.OwnsMany("Customers.Domain.Entities.CustomerAddress", "CustomerAddresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("CustomerId");

                            b1.HasIndex("Label", "CustomerId")
                                .IsUnique();

                            b1.ToTable("CustomerAddresses", "customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("Shared.Domain.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("CustomerAddressId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Area")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Area");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("City");

                                    b2.Property<string>("StreetName")
                                        .HasColumnType("text")
                                        .HasColumnName("StreetName");

                                    b2.Property<string>("StreetNumber")
                                        .HasColumnType("text")
                                        .HasColumnName("StreetNumber");

                                    b2.HasKey("CustomerAddressId");

                                    b2.ToTable("CustomerAddresses", "customers");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerAddressId");

                                    b2.OwnsOne("Shared.Domain.ValueObjects.Coordinates", "Coordinates", b3 =>
                                        {
                                            b3.Property<Guid>("AddressCustomerAddressId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("Latitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Latitude");

                                            b3.Property<double>("Longitude")
                                                .HasColumnType("double precision")
                                                .HasColumnName("Longitude");

                                            b3.HasKey("AddressCustomerAddressId");

                                            b3.ToTable("CustomerAddresses", "customers");

                                            b3.WithOwner()
                                                .HasForeignKey("AddressCustomerAddressId");
                                        });

                                    b2.Navigation("Coordinates")
                                        .IsRequired();
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("CustomerAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
