<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernal\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\Food.Domain\Food.Domain.csproj" />
    <ProjectReference Include="..\Food.Contracts\Food.Contracts.csproj" />
  </ItemGroup>

</Project>
