// <auto-generated />
using System;
using Menus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Menus.Infrastructure.Migrations
{
    [DbContext(typeof(MenusDbContext))]
    [Migration("20260210002904_UniqueMealNamePerRestaurant")]
    partial class UniqueMealNamePerRestaurant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("menus")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Menus.Domain.Entities.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique();

                    b.ToTable("MenuCategories", "menus");
                });

            modelBuilder.Entity("Menus.Domain.Entities.MenuMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique();

                    b.ToTable("MenuMeals", "menus");
                });

            modelBuilder.Entity("Menus.Domain.Entities.MenuMeal", b =>
                {
                    b.HasOne("Menus.Domain.Entities.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Menus.Domain.Entities.MealSize", "Sizes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("MealId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("MealId");

                            b1.ToTable("MealSizes", "menus");

                            b1.WithOwner()
                                .HasForeignKey("MealId");

                            b1.OwnsOne("Shared.Kernal.ValueObjects.Nutrition", "Nutrition", b2 =>
                                {
                                    b2.Property<Guid>("MealSizeId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("CalciumMg")
                                        .HasColumnType("numeric")
                                        .HasColumnName("CalciumMg");

                                    b2.Property<decimal>("Calories")
                                        .HasColumnType("numeric")
                                        .HasColumnName("Calories");

                                    b2.Property<decimal>("Cholesterol")
                                        .HasColumnType("numeric")
                                        .HasColumnName("Cholesterol");

                                    b2.Property<decimal>("DietaryFiber")
                                        .HasColumnType("numeric")
                                        .HasColumnName("DietaryFiber");

                                    b2.Property<decimal>("IronMg")
                                        .HasColumnType("numeric")
                                        .HasColumnName("IronMg");

                                    b2.Property<decimal>("PotassiumMg")
                                        .HasColumnType("numeric")
                                        .HasColumnName("PotassiumMg");

                                    b2.Property<decimal>("Protein")
                                        .HasColumnType("numeric")
                                        .HasColumnName("Protein");

                                    b2.Property<decimal>("SaturatedFat")
                                        .HasColumnType("numeric")
                                        .HasColumnName("SaturatedFat");

                                    b2.Property<decimal>("SodiumMg")
                                        .HasColumnType("numeric")
                                        .HasColumnName("SodiumMg");

                                    b2.Property<decimal>("SugarGrams")
                                        .HasColumnType("numeric")
                                        .HasColumnName("SugarGrams");

                                    b2.Property<decimal>("TotalCarbohydrate")
                                        .HasColumnType("numeric")
                                        .HasColumnName("TotalCarbohydrate");

                                    b2.Property<decimal>("TotalFat")
                                        .HasColumnType("numeric")
                                        .HasColumnName("TotalFat");

                                    b2.Property<decimal>("TransFat")
                                        .HasColumnType("numeric")
                                        .HasColumnName("TransFat");

                                    b2.Property<decimal>("VitaminAMcg")
                                        .HasColumnType("numeric")
                                        .HasColumnName("VitaminAMcg");

                                    b2.Property<decimal>("VitaminCMg")
                                        .HasColumnType("numeric")
                                        .HasColumnName("VitaminCMg");

                                    b2.Property<decimal>("VitaminD")
                                        .HasColumnType("numeric")
                                        .HasColumnName("VitaminD");

                                    b2.HasKey("MealSizeId");

                                    b2.ToTable("MealSizes", "menus");

                                    b2.WithOwner()
                                        .HasForeignKey("MealSizeId");
                                });

                            b1.OwnsOne("Shared.Kernal.ValueObjects.Price", "Price", b2 =>
                                {
                                    b2.Property<Guid>("MealSizeId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_currency");

                                    b2.HasKey("MealSizeId");

                                    b2.ToTable("MealSizes", "menus");

                                    b2.WithOwner()
                                        .HasForeignKey("MealSizeId");
                                });

                            b1.Navigation("Nutrition")
                                .IsRequired();

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("Sizes");
                });
#pragma warning restore 612, 618
        }
    }
}
