// <auto-generated />
using System;
using System.Collections.Generic;
using Menus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Menus.Infrastructure.Migrations
{
    [DbContext(typeof(MenusDbContext))]
    [Migration("20260117125416_RemoveFoodFromMenuModule")]
    partial class RemoveFoodFromMenuModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("menus")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Menus.Domain.Entities.MealSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MenuMealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Nutrition", "Menus.Domain.Entities.MealSize.Nutrition#Nutrition", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("CalciumMg")
                                .HasColumnType("numeric")
                                .HasColumnName("CalciumMg");

                            b1.Property<decimal>("Calories")
                                .HasColumnType("numeric")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("Cholesterol")
                                .HasColumnType("numeric")
                                .HasColumnName("Cholesterol");

                            b1.Property<decimal>("DietaryFiber")
                                .HasColumnType("numeric")
                                .HasColumnName("DietaryFiber");

                            b1.Property<decimal>("IronMg")
                                .HasColumnType("numeric")
                                .HasColumnName("IronMg");

                            b1.Property<decimal>("PotassiumMg")
                                .HasColumnType("numeric")
                                .HasColumnName("PotassiumMg");

                            b1.Property<decimal>("Protein")
                                .HasColumnType("numeric")
                                .HasColumnName("Protein");

                            b1.Property<decimal>("SaturatedFat")
                                .HasColumnType("numeric")
                                .HasColumnName("SaturatedFat");

                            b1.Property<decimal>("SodiumMg")
                                .HasColumnType("numeric")
                                .HasColumnName("SodiumMg");

                            b1.Property<decimal>("SugarGrams")
                                .HasColumnType("numeric")
                                .HasColumnName("SugarGrams");

                            b1.Property<decimal>("TotalCarbohydrate")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalCarbohydrate");

                            b1.Property<decimal>("TotalFat")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalFat");

                            b1.Property<decimal>("TransFat")
                                .HasColumnType("numeric")
                                .HasColumnName("TransFat");

                            b1.Property<decimal>("VitaminAMcg")
                                .HasColumnType("numeric")
                                .HasColumnName("VitaminAMcg");

                            b1.Property<decimal>("VitaminCMg")
                                .HasColumnType("numeric")
                                .HasColumnName("VitaminCMg");

                            b1.Property<decimal>("VitaminD")
                                .HasColumnType("numeric")
                                .HasColumnName("VitaminD");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Price", "Menus.Domain.Entities.MealSize.Price#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MenuMealId");

                    b.ToTable("MealSizes", "menus");
                });

            modelBuilder.Entity("Menus.Domain.Entities.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "Name")
                        .IsUnique();

                    b.ToTable("MenuCategories", "menus");
                });

            modelBuilder.Entity("Menus.Domain.Entities.MenuMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuMeals", "menus");
                });

            modelBuilder.Entity("Menus.Domain.Entities.MealSize", b =>
                {
                    b.HasOne("Menus.Domain.Entities.MenuMeal", null)
                        .WithMany("Sizes")
                        .HasForeignKey("MenuMealId");
                });

            modelBuilder.Entity("Menus.Domain.Entities.MenuMeal", b =>
                {
                    b.HasOne("Menus.Domain.Entities.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Menus.Domain.Entities.MenuMeal", b =>
                {
                    b.Navigation("Sizes");
                });
#pragma warning restore 612, 618
        }
    }
}
