// <auto-generated />
using System;
using System.Collections.Generic;
using Food.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Food.Infrastructure.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    partial class FoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Food")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Food.Domain.Entities.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("NutritionPer100g", "Food.Domain.Entities.Food.NutritionPer100g#Nutrition", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("CalciumMg")
                                .HasColumnType("numeric")
                                .HasColumnName("CalciumMg");

                            b1.Property<decimal>("Calories")
                                .HasColumnType("numeric")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("Cholesterol")
                                .HasColumnType("numeric")
                                .HasColumnName("Cholesterol");

                            b1.Property<decimal>("DietaryFiber")
                                .HasColumnType("numeric")
                                .HasColumnName("DietaryFiber");

                            b1.Property<decimal>("IronMg")
                                .HasColumnType("numeric")
                                .HasColumnName("IronMg");

                            b1.Property<decimal>("PotassiumMg")
                                .HasColumnType("numeric")
                                .HasColumnName("PotassiumMg");

                            b1.Property<decimal>("Protein")
                                .HasColumnType("numeric")
                                .HasColumnName("Protein");

                            b1.Property<decimal>("SaturatedFat")
                                .HasColumnType("numeric")
                                .HasColumnName("SaturatedFat");

                            b1.Property<decimal>("SodiumMg")
                                .HasColumnType("numeric")
                                .HasColumnName("SodiumMg");

                            b1.Property<decimal>("SugarGrams")
                                .HasColumnType("numeric")
                                .HasColumnName("SugarGrams");

                            b1.Property<decimal>("TotalCarbohydrate")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalCarbohydrate");

                            b1.Property<decimal>("TotalFat")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalFat");

                            b1.Property<decimal>("TransFat")
                                .HasColumnType("numeric")
                                .HasColumnName("TransFat");

                            b1.Property<decimal>("VitaminAMcg")
                                .HasColumnType("numeric")
                                .HasColumnName("VitaminAMcg");

                            b1.Property<decimal>("VitaminCMg")
                                .HasColumnType("numeric")
                                .HasColumnName("VitaminCMg");

                            b1.Property<decimal>("VitaminD")
                                .HasColumnType("numeric")
                                .HasColumnName("VitaminD");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("Foods", "Food");
                });
#pragma warning restore 612, 618
        }
    }
}
