// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurants.Infrastructure.Persistence;

#nullable disable

namespace Restaurants.Infrastructure.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("restaurants")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Restaurants.Domain.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Restaurants", "restaurants");
                });

            modelBuilder.Entity("Restaurants.Domain.Entities.RestaurantApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BranchCount")
                        .HasColumnType("integer");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyMobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OwnerFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerMobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RestaurantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("MainBranchLocation", "Restaurants.Domain.Entities.RestaurantApplication.MainBranchLocation#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Area");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("StreetName")
                                .HasColumnType("text")
                                .HasColumnName("StreetName");

                            b1.Property<string>("StreetNumber")
                                .HasColumnType("text")
                                .HasColumnName("StreetNumber");

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinates", "Restaurants.Domain.Entities.RestaurantApplication.MainBranchLocation#Address.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Longitude");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("BrandName")
                        .IsUnique();

                    b.HasIndex("CompanyEmail")
                        .IsUnique();

                    b.ToTable("RestaurantApplications", "restaurants");
                });

            modelBuilder.Entity("Restaurants.Domain.Entities.RestaurantBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "Restaurants.Domain.Entities.RestaurantBranch.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Area");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("StreetName")
                                .HasColumnType("text")
                                .HasColumnName("StreetName");

                            b1.Property<string>("StreetNumber")
                                .HasColumnType("text")
                                .HasColumnName("StreetNumber");

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinates", "Restaurants.Domain.Entities.RestaurantBranch.Address#Address.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Longitude");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PhoneNumber", "Restaurants.Domain.Entities.RestaurantBranch.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");
                        });

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("RestaurantBranches", "restaurants");
                });

            modelBuilder.Entity("Restaurants.Domain.Entities.RestaurantBranch", b =>
                {
                    b.HasOne("Restaurants.Domain.Entities.Restaurant", null)
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Restaurants.Domain.ValueObjects.DailySchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Day")
                                .HasColumnType("text");

                            b1.HasKey("BranchId", "Day");

                            b1.ToTable("DailySchedule", "restaurants");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");

                            b1.OwnsOne("Restaurants.Domain.ValueObjects.OperatingHours", "OperatingHours", b2 =>
                                {
                                    b2.Property<Guid>("DailyScheduleBranchId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("DailyScheduleDay")
                                        .HasColumnType("text");

                                    b2.Property<TimeOnly>("ClosingTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("ClosingTime");

                                    b2.Property<TimeOnly>("OpeningTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("OpeningTime");

                                    b2.HasKey("DailyScheduleBranchId", "DailyScheduleDay");

                                    b2.ToTable("DailySchedule", "restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("DailyScheduleBranchId", "DailyScheduleDay");
                                });

                            b1.Navigation("OperatingHours")
                                .IsRequired();
                        });

                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
