// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Subscriptions.Infrastructure.Persistence;

#nullable disable

namespace Subscriptions.Infrastructure.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    [Migration("20260311003958_Subscriptiosn_AddAddress")]
    partial class Subscriptiosn_AddAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Subscriptions")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Subscriptions.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeliveryAddressId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("DeliveryAddress", "Subscriptions.Domain.Entities.Subscription.DeliveryAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StreetName")
                                .HasColumnType("text");

                            b1.Property<string>("StreetNumber")
                                .HasColumnType("text");

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinates", "Subscriptions.Domain.Entities.Subscription.DeliveryAddress#Address.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("Longitude");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TimeFrame", "Subscriptions.Domain.Entities.Subscription.TimeFrame#DeliveryTimeFrame", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly>("From")
                                .HasColumnType("time without time zone");

                            b1.Property<TimeOnly>("To")
                                .HasColumnType("time without time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TotalPrice", "Subscriptions.Domain.Entities.Subscription.TotalPrice#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Subscriptions", "Subscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryTime", "\"EndDate\" > \"StartDate\"");
                        });
                });

            modelBuilder.Entity("Subscriptions.Domain.Entities.Subscription", b =>
                {
                    b.OwnsMany("Subscriptions.Domain.ValueObjects.SubscriptionDeliveryDay", "DeliveryDays", b1 =>
                        {
                            b1.Property<string>("Day")
                                .HasColumnType("text");

                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Day", "SubscriptionId");

                            b1.HasIndex("SubscriptionId");

                            b1.ToTable("SubscriptionDeliveryDays", "Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsMany("Subscriptions.Domain.ValueObjects.SubscriptionMeal", "SubscriptionMeals", b1 =>
                        {
                            b1.Property<Guid>("MealId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SizeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("MealId", "SizeId", "SubscriptionId");

                            b1.HasIndex("SubscriptionId");

                            b1.ToTable("SubscriptionMeals", "Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");

                            b1.OwnsOne("Shared.Domain.ValueObjects.Price", "PriceAtSubscription", b2 =>
                                {
                                    b2.Property<Guid>("SubscriptionMealMealId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SubscriptionMealSizeId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SubscriptionMealSubscriptionId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("SubscriptionMealMealId", "SubscriptionMealSizeId", "SubscriptionMealSubscriptionId");

                                    b2.ToTable("SubscriptionMeals", "Subscriptions");

                                    b2.WithOwner()
                                        .HasForeignKey("SubscriptionMealMealId", "SubscriptionMealSizeId", "SubscriptionMealSubscriptionId");
                                });

                            b1.Navigation("PriceAtSubscription")
                                .IsRequired();
                        });

                    b.Navigation("DeliveryDays");

                    b.Navigation("SubscriptionMeals");
                });
#pragma warning restore 612, 618
        }
    }
}
