<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Orders\Orders.Contract\Orders.Contract.csproj" />
    <ProjectReference Include="..\..\..\SharedKernal\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\..\Customers\Customers.Contracts\Customers.Contracts.csproj" />
    <ProjectReference Include="..\..\Menus\Menus.Contracts\Menus.Contracts.csproj" />
    <ProjectReference Include="..\..\Restaurants\Restaurants.Contracts\Restaurants.Contracts.csproj" />
    <ProjectReference Include="..\Subscriptions.Domain\Subscriptions.Domain.csproj" />
  </ItemGroup>
  

</Project>