<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b81a72b3-7275-4801-8cc0-37c71b750daf</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="logs\**" />
    <Content Remove="logs\**" />
    <EmbeddedResource Remove="logs\**" />
    <None Remove="logs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules\Customers\Customers.Application\Customers.Application.csproj" />
    <ProjectReference Include="..\Modules\Customers\Customers.Infrastructure\Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Customers\Customers.Presentation\Customers.Presentation.csproj" />
    <ProjectReference Include="..\Modules\Food\Food.Infrastructure\Food.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Food\Food.Presentation\Food.Presentation.csproj" />
    <ProjectReference Include="..\Modules\Menus\Menus.Infrastructure\Menus.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Menus\Menus.Presentation\Menus.Presentation.csproj" />
    <ProjectReference Include="..\Modules\Orders\Orders.Infrastructure\Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Orders\Orders.Presentation\Orders.Presentation.csproj" />
    <ProjectReference Include="..\Modules\Restaurants\Restaurants.Application\Restaurants.Application.csproj" />
    <ProjectReference Include="..\Modules\Restaurants\Restaurants.Infrastructure\Restaurants.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Restaurants\Restaurants.Presentation\Restaurants.Presentation.csproj" />
    <ProjectReference Include="..\Modules\Subscriptions\Subscriptions.Infrastructure\Subscriptions.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Subscriptions\Subscriptions.Presentation\Subscriptions.Presentation.csproj" />
  </ItemGroup>

</Project>